name: Deploy

on:
  push:
    branches: [ master, feature/awsdeploy ]

permissions:
  id-token: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: deploy-front
          aws-region: ${{ secrets.AWS_REGION }}
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.x
          cache: 'npm'
        
      - name: Build deploy artifacts
        run: |
          npm install
          npm run build
      # Deploy the files to AWS
      - name: Deploy to AWS
        run: aws s3 sync $GITHUB_WORKSPACE/out s3://${{ secrets.AWS_BUCKET }}/
